--- 
twitter: 
  CONSUMER_SECRET: YOUR_CONSUMER_SECRET
  OAUTH_TOKEN: YOUR_OAUTH_TOKEN
  OAUTH_TOKEN_SECRET: YOUR_OAUTH_TOKEN_SECRET
  CONSUMER_KEY: YOUR_CONSUMER_KEY
feeds: 
  YOUR_BLOG_NAME: 
    link: YOUR_FEED_URL
